// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzV19w0Z_BeNH1VKuqXVNcHquBMxTZi0s',
    appId: '1:371559088399:web:b2e5d5f7b57ed933f37e7a',
    messagingSenderId: '371559088399',
    projectId: 'grace-fresh-market-647f0',
    authDomain: 'grace-fresh-market-647f0.firebaseapp.com',
    storageBucket: 'grace-fresh-market-647f0.firebasestorage.app',
    measurementId: 'G-Z5RQW9VH4M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxzka2KVc4Rt00eCqcHjSNJw1QkotsyXU',
    appId: '1:371559088399:android:fed237ba25c7b3bcf37e7a',
    messagingSenderId: '371559088399',
    projectId: 'grace-fresh-market-647f0',
    storageBucket: 'grace-fresh-market-647f0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDINFxbS83rrAW_adwrfZshz56T8TEp8M',
    appId: '1:371559088399:ios:453f09e122630ad3f37e7a',
    messagingSenderId: '371559088399',
    projectId: 'grace-fresh-market-647f0',
    storageBucket: 'grace-fresh-market-647f0.firebasestorage.app',
    iosBundleId: 'com.gracefresh.market.graceFreshMarket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDINFxbS83rrAW_adwrfZshz56T8TEp8M',
    appId: '1:371559088399:ios:453f09e122630ad3f37e7a',
    messagingSenderId: '371559088399',
    projectId: 'grace-fresh-market-647f0',
    storageBucket: 'grace-fresh-market-647f0.firebasestorage.app',
    iosBundleId: 'com.gracefresh.market.graceFreshMarket',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzV19w0Z_BeNH1VKuqXVNcHquBMxTZi0s',
    appId: '1:371559088399:web:3d1f35a2994c0e11f37e7a',
    messagingSenderId: '371559088399',
    projectId: 'grace-fresh-market-647f0',
    authDomain: 'grace-fresh-market-647f0.firebaseapp.com',
    storageBucket: 'grace-fresh-market-647f0.firebasestorage.app',
    measurementId: 'G-R7V8CWXMZ2',
  );
}
